name: Push to Hugging Face hub
on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/hf_space.yml'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        with:
          fetch-depth: 0
          lfs: true
          # ref: 61633533fbf1da092f89202d530e7834e1bab8e5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Prepare and push to HF
        run: |

          # Prepare space
          # mkdir $SPACE_NAME
          # cd $SPACE_NAME
          # cd ..
          cp .github/workflows/hf_readme.md README.md
          cp examples/space.py app.py
          cp -rf ./src/kolani_tts .

          # Editor deps
          uv export --no-hashes --no-emit-project > requirements.txt
          echo "gradio" >> requirements.txt            
          # Kolani deps
          # Phonikud deps
          # Copy files
          # cp -rf ../src/kolani_tts .

          # Git
          git lfs install
          rm -rf .git
          rm -rf .gitignore

          git init
          git lfs track "*.onnx"
          git branch -M main
          git config --global user.email "thewh1teagle"
          git config --global user.name "thewh1teagle"
          git remote add origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          
          wget --progress=bar:force https://huggingface.co/thewh1teagle/phonikud-onnx/resolve/main/phonikud-1.0.int8.onnx -O phonikud-1.0.int8.onnx
          wget --progress=bar:force https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx -O en_US-ryan-medium.onnx
          wget --progress=bar:force https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json -O en_US-ryan-medium.onnx.json

          git add .
          git commit -m "latest"
          git push --force origin main
          

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "thewh1teagle"
          SPACE_NAME: "kolani-tts"